POST http://localhost:6666/demo/test
Content-Type: application/json

{}

###
POST http://localhost:6666/demo/listUser
Content-Type: application/json

{}

###
POST http://localhost:6666/demo/addUser
Content-Type: application/json

{}

###
